from mininet.topo import Topo
class MyTopo(Topo):
    def __init__(self):
        Topo.__init__(self)
        # Add nodes (hosts and switches)
        h1 = self.addHost('h1', ip='192.168.0.1')
        h2 = self.addHost('h2', ip='192.168.0.2')
        h3 = self.addHost('h3', ip='192.168.0.3')
        h4 = self.addHost('h4', ip='192.168.0.4')
        h5 = self.addHost('h5', ip='192.168.0.5')
        h6 = self.addHost('h6', ip='192.168.0.6')
        server = self.addHost('server', ip='192.168.0.7')
        cs1 = self.addSwitch('cs1')
        es1 = self.addSwitch('es1')
        es2 = self.addSwitch('es2')
        as1 = self.addSwitch('as1')
        as2 = self.addSwitch('as2')
        as3 = self.addSwitch('as3')
        as4 = self.addSwitch('as4')
        # Add links
        self.addLink(cs1, es1)
        self.addLink(cs1, es2)
        self.addLink(es1, as1)
        self.addLink(es1, as2)
        self.addLink(es2, as3)
        self.addLink(es2, as4)
        self.addLink(as1, h1)
        self.addLink(as1, h2)
        self.addLink(as2, h3)
        self.addLink(as2, h4)
        self.addLink(as3, h5)
        self.addLink(as3, h6)
        self.addLink(as4, server)
topos = {'mytopo': (lambda: MyTopo())}
